// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Single key-value entry from a KV bucket.
type KVEntry struct {
	// Key name
	Key string `json:"key"`
	// Value stored under this key (as UTF-8 string)
	Value string `json:"value"`
	// Revision number (monotonically increasing version)
	Revision int `json:"revision"`
	// Timestamp when this revision was created, in RFC3339 format
	Created string `json:"created"`
}

// NATS JetStream Key-Value store information.
// Represents metadata about a KV bucket including its configuration and current state.
type KeyValue struct {
	// Name of the KV bucket
	Bucket string `json:"bucket"`
	// Maximum number of history entries per key (how many past values are retained)
	History int `json:"history"`
	// Time-to-live for keys in seconds. 0 means keys do not expire
	TTL int `json:"ttl"`
	// Storage backend type (e.g. JetStream)
	Storage string `json:"storage"`
	// Total size of the KV store in bytes
	Bytes int `json:"bytes"`
	// Total number of key-value pairs in the store
	Values int `json:"values"`
	// Whether the KV store data is compressed
	IsCompressed bool `json:"isCompressed"`
}

type Mutation struct {
}

type Query struct {
}

// NATS JetStream stream information.
// Represents metadata about a stream including its configuration and current runtime state.
type StreamInfo struct {
	// Unique name of the stream
	Name string `json:"name"`
	// List of subject filters the stream is listening on (e.g. ['orders.>', 'payments.*'])
	Subjects []string `json:"subjects"`
	// Message retention policy: Limits (by count/size/age), Interest (while consumers exist), or WorkQueue (ack-based removal)
	Retention string `json:"retention"`
	// Maximum number of consumers allowed on this stream. -1 means unlimited
	MaxConsumers int `json:"maxConsumers"`
	// Maximum number of messages stored in the stream. -1 means unlimited
	MaxMsgs int `json:"maxMsgs"`
	// Maximum total size of messages in the stream in bytes. -1 means unlimited
	MaxBytes int `json:"maxBytes"`
	// Storage type: File (persistent to disk) or Memory (in-memory only)
	Storage string `json:"storage"`
	// Number of stream replicas for high availability in a NATS cluster
	Replicas int `json:"replicas"`
	// Current number of messages stored in the stream
	Messages int `json:"messages"`
	// Current total size of all messages in the stream in bytes
	Bytes int `json:"bytes"`
	// Current number of active consumers subscribed to this stream
	Consumers int `json:"consumers"`
	// Stream creation timestamp in RFC3339 format
	Created string `json:"created"`
}
